version: '3'

services:
  chrome:
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    volumes:
      - /dev/shm:/dev/shm
    image: selenium/standalone-chrome-debug:3.141.59-neon
    ports:
      - '5900:5900'
  codeception:
    image: codeception/codeception
    volumes:
      - ./:/project
    ports:
      - '8000:8000'
    depends_on:
      - chrome

